import HeroSection from './_components/hero-section'

export default function HomePage() {
	return (
		<main>
			<HeroSection />
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
			<p>lorem</p>
		</main>
	)
}
